### ISSUE TITLE
ed.on is not a function

### ISSUE THREAD

**Issue by gazayas** [spohlenz/tinymce-rails#239]
When doing setup in the `tinymce.yml` file or directly on the page with `tinymce.init({ ... })`, it will log the editor to the console:

```javascript
setup: function(ed) { console.log(ed) }
```

but if I try to use `ed.on()` it just says that ed.on is not a function.

If I remove `setup`, the editor shows up just fine.
I also uninstalled the gem and just used tinymce hardcoded into the view, and it works just fine with setup and ed.on

Here's how my `tinymce.yml` file looks like:
```yml
toolbar:
  - italic
menubar: false
selector: 'textarea'
height: 275
forced_root_block : ""
setup: function(ed) {
    ed.on('init', function()
    {
      this.getDoc().body.style.fontSize = '16px';
    });
  }
```
