### ISSUE TITLE
Compiled JS file is empty

### ISSUE THREAD

**Issue by ianrandmckenzie** [spohlenz/tinymce-rails#258]
My Rails application.js has tried both `//=require tinymce` as well as `//=require tinymce-jquery` and the files loaded are completely empty. Did the new version not get copied over properly? I'm on TinyMCE version 5.0.13.

**Comment by ianrandmckenzie** [comment]
I also tried 5.0.12 and 5.0.10 and the JS files are empty as well.

**Comment by ianrandmckenzie** [comment]
Okay, I think I found the problem. The editor wasn't loading properly because I was using `<%= tinymce :alternate %>` — when I use <%= tinymce %>`, it works just fine. Is there something wrong with my configuration?

```yml
default:
  plugins:
    - image
    - link

alternate:
  <<: *default
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table
```

It's a straight up copy/paste from the README.

**Comment by ianrandmckenzie** [comment]
If I change the `config/tinymce.yml` to:

```yml
default: &default
  plugins:
    - image
    - link

alternate:
  <<: *default
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table
```

I no longer get an error when loading `<%= tinymce %>` or `<%= tinymce :alternate %>`, however, when I do `:alternate` the editor interface does not load at all.

Is there perhaps an interaction with my Ruby/Rails versions? I'm on Ruby 2.6.3 and Rails 6.0.0.rc1
