### ISSUE TITLE
valid_styles compiles incorrectly for v6

### ISSUE THREAD

**Issue by aseroff** [spohlenz/tinymce-rails#289]
Based on the [documentation](https://www.tiny.cloud/docs/tinymce/6/content-filtering/#example-using-valid_styles), it seems that it requires element types to be put in quotes. However, the yml is compiled without them.

Example, a necessary piece of configuration to use underline, strikethrough, alignment, indentation, and advanced lists:
```
valid_styles:
  p: 'text-align, padding-left'
  span: 'text-decoration'
  ol: 'list-style-type'
  li: 'list-style-type'
```

Expected compilation:
```
valid_styles: {
    'p': 'text-align, padding-left'
    'span': 'text-decoration'
    'ol': 'list-style-type'
    'li': 'list-style-type'
}
```
  
  Actual compilation:
```
valid_styles: {
  p: 'text-align, padding-left'
  span: 'text-decoration'
  ol: 'list-style-type'
  li: 'list-style-type'
}
  ```

As a result it seems to not work. However, no error is thrown unless you use the '*' key, which, without quotes, leads to an error on init.
